Update 03.09.04-FW21
Signed-off-by: Thomas Brandt <Thomas.Brandt@wago.com>

diff --git a/projectroot/etc/init.d/lighttpd b/projectroot/etc/init.d/lighttpd
--- a/projectroot/etc/init.d/lighttpd
+++ b/projectroot/etc/init.d/lighttpd
@@ -1,125 +1,205 @@
 #!/bin/bash
-
+#-----------------------------------------------------------------------------#
 # This Source Code Form is subject to the terms of the Mozilla Public
 # License, v. 2.0. If a copy of the MPL was not distributed with this
 # file, You can obtain one at http://mozilla.org/MPL/2.0/.
 #
-# Copyright (c) 2021 WAGO Kontakttechnik GmbH & Co. KG
-
+# Copyright (c) 2011-2021 WAGO GmbH & Co. KG
+#-----------------------------------------------------------------------------#
+#-----------------------------------------------------------------------------#
+# Script:   /etc/init.d/lighttpd
 #
-# lighttpd start script
+# Brief:    System V init script for lighttpd.
 #
+# Author:   PEn:  WAGO GmbH & Co. KG
+# Author:   MaHe: WAGO GmbH & Co. KG
+#-----------------------------------------------------------------------------#
 
 PREFIX="lighttpd: "
 LIGHTTPD="/usr/sbin/lighttpd"
 LIGHTTPD_PROC="lighttpd"
-LIGHTTPD_PIDFILE="/var/run/lighttpd.pid"
 LIGHTTPD_CONF="/etc/lighttpd/lighttpd.conf"
 LIGHTTPD_LOGDIR="/var/log/lighttpd"
 LIGHTTPD_PHP_SESSION_DIR="/var/run/php/sessions"
 START_STOP_DAEMON="/sbin/start-stop-daemon"
 
-# Utility function to store process id after service startup
-store_pidfile()
-{
-	# Determine the pid of lighttpd by filter out own pid.
-	# One will be this script itself because it's named equally.
-	local own_pid="$BASHPID"
-	local lighttpd_pids
-	lighttpd_pids="$(pidof "${LIGHTTPD_PROC}")"
-	for pid in $lighttpd_pids; do
-		if [[ "$pid" != "$own_pid" ]]; then
-			echo -n "$pid" > "${LIGHTTPD_PIDFILE}"
-		fi
-	done
-}
-
-# Utility function to remove PID-File after stopping the service
-remove_pidfile()
-{
-	rm -f "${LIGHTTPD_PIDFILE}"
-}
+# Somehow we rarly get SIGHUP signals, which can cause
+# "start" or "stop" to be interrupted unexpectedly.
+# This can cause "reload" to not work as intended.
+# This trap handles SIGHUP to work around this problem.
+trap "{ }" SIGHUP
 
 # Utility function to create a directory and assign appropriate 
 # permissions as required by the service
-create_directry_if_needed()
+create_directory_if_needed()
 {
-	local directory="$1"
-	if [ ! -d "${directory}" ]; then
-		mkdir -p "${directory}"
-		chmod 700 "${directory}"
-		chown www:www "${directory}"
+    local directory="$1"
+    if [[ ! -d "${directory}" ]]; then
+        mkdir -p "${directory}"
+        chmod 700 "${directory}"
+        chown www:www "${directory}"
     fi
 }
 
-# Start the service 
-start()
+status_check()
 {
-	create_directry_if_needed "${LIGHTTPD_LOGDIR}"
-	create_directry_if_needed "${LIGHTTPD_PHP_SESSION_DIR}"
-	$START_STOP_DAEMON --quiet --start --exec "${LIGHTTPD}" -- -f "${LIGHTTPD_CONF}"
-	return $?
+    local own_pid="$BASHPID"
+    local lighttpd_pids
+    local pid_count=0
+    lighttpd_pids="$(pidof "${LIGHTTPD_PROC}")"
+    for pid in $lighttpd_pids; do
+        if [[ "$pid" != "$own_pid" ]]; then
+            pid_count=$((pid_count + 1))
+        fi
+    done
+    if [[ $pid_count -eq 1 ]]; then
+        return 0
+    elif [[ $pid_count -lt 1 ]]; then
+        # No lighttpd process active
+        return 1
+    else
+        # Multiple lighttpd processes active => starting but not started, yet
+        return 2
+    fi
 }
 
-# Stop the service 
+wait_for_start()
+{
+    local result=0
+
+    echo -n "${PREFIX}starting"
+    local try_count=0
+    while ! status_check; do
+        try_count=$((try_count+1))
+        if [[ $try_count -gt 20 ]]; then
+            result=1
+            break
+        fi
+        echo -n "."
+        usleep 100000
+    done
+    echo ""
+
+    return $result
+}
+
+start()
+{
+    local result
+    create_directory_if_needed "${LIGHTTPD_LOGDIR}"
+    create_directory_if_needed "${LIGHTTPD_PHP_SESSION_DIR}"
+    $START_STOP_DAEMON --quiet --start --exec "${LIGHTTPD}" -- -f "${LIGHTTPD_CONF}"
+    result=$?
+    if [[ $result -eq 0 ]]; then
+        wait_for_start
+        result=$?
+    fi
+
+    return $result
+}
+
+wait_for_stop()
+{
+    local result=0
+
+    echo -n "${PREFIX}stopping"
+    local try_count=0
+    while $START_STOP_DAEMON --stop -t --quiet --exec "${LIGHTTPD}"; do
+        try_count=$((try_count+1))
+        if [[ $try_count -gt 20 ]]; then
+            result=1
+            break
+        fi
+        echo -n "."
+        usleep 100000
+    done
+    echo ""
+
+    return $result
+}
+
 stop()
 {
+    local result
+
     $START_STOP_DAEMON --quiet --stop --oknodo --exec "${LIGHTTPD}"
-	return $?
+    result=$?
+    if [[ $result -eq 0 ]]; then
+        wait_for_stop
+        result=$?
+    fi
+
+    return $result
 }
 
 # Reload configuration of the service
 reload()
 {
-	local retval=-1
-	store_pidfile
-	if $START_STOP_DAEMON --stop --signal SIGINT --oknodo --quiet --pidfile "${LIGHTTPD_PIDFILE}" --exec "${LIGHTTPD}"; then
-		while start-stop-daemon --stop -t --quiet --pidfile "${LIGHTTPD_PIDFILE}" --exec "${LIGHTTPD}"; do
-			usleep 10000;
-		done
-		if start; then
-			retval=0
-		# Startup may fail rarely, try once more in that case
-		elif sleep 1 && start; then
-			retval=0
-		fi
-	fi
-    remove_pidfile
-	return $retval;	
+    local result=1
+    if $START_STOP_DAEMON --stop --signal SIGINT --oknodo --quiet --exec "${LIGHTTPD}"; then
+        wait_for_stop
+        if start; then
+            result=0
+        # Startup may fail rarely, try once more in that case
+        elif sleep 1 && start; then
+            result=0
+        fi
+    fi
+
+    return $result
 }
 
 case $1 in
 
-	start)
-		echo "${PREFIX}starting"
-		if start; then
-			echo "${PREFIX}done"
-		else
-			echo "${PREFIX}error, could not start server"
-		fi
-		;;
+    start)
+        echo "${PREFIX}start"
+        if start; then
+            echo "${PREFIX}start done"
+            exit 0
+        else
+            echo "${PREFIX}error, could not start server" >&2
+            exit 1
+        fi
+        ;;
 
-	stop)
-		echo "${PREFIX}stopping"
-		if stop; then
-			echo "${PREFIX}done"
-		else
-			echo "${PREFIX}error, could not stop server"
-		fi
-		;;
+    stop)
+        echo "${PREFIX}stop"
+        if stop; then
+            echo "${PREFIX}stop done"
+            exit 0
+        else
+            echo "${PREFIX}error, could not stop server" >&2
+            exit 1
+        fi
+        ;;
 
-	reload)
-		echo "${PREFIX}reloading"
-		if reload; then
-			echo "${PREFIX}done"
-		else
-			echo "${PREFIX}error, could not reload server"
-		fi
-		;;
+    status)
+        echo "${PREFIX}status check"
+        if status_check; then
+            echo "${PREFIX}running"
+            exit 0
+        else
+            echo "${PREFIX}stopped"
+            # This is not really an error case but for an automated status check
+            # an other return code than 0 is used here
+            exit 1
+        fi
+        ;;
 
-	*)
-		echo "${PREFIX}usage: ${0} [start|stop|reload]"
-		exit 1
-		;;
+    reload)
+        echo "${PREFIX}reload"
+        if reload; then
+            echo "${PREFIX}reload done"
+            exit 0
+        else
+            echo "${PREFIX}error, could not reload server" >&2
+            exit 1
+        fi
+        ;;
+
+    *)
+        echo "${PREFIX}usage: ${0} [start|stop|status|reload]" >&2
+        exit 1
+        ;;
 
 esac
