Update V03.01.07-FW13

diff --git a/projectroot.wago-pfcXXX/etc/init.d/dockerd b/projectroot.wago-pfcXXX/etc/init.d/dockerd
--- a/projectroot.wago-pfcXXX/etc/init.d/dockerd
+++ b/projectroot.wago-pfcXXX/etc/init.d/dockerd
@@ -1,38 +1,62 @@
 #!/bin/bash
 
+#-----------------------------------------------------------------------------#
 # This Source Code Form is subject to the terms of the Mozilla Public
 # License, v. 2.0. If a copy of the MPL was not distributed with this
 # file, You can obtain one at http://mozilla.org/MPL/2.0/.
 #
-# Copyright (c) 2018 WAGO Kontakttechnik GmbH & Co. KG
+# Copyright (c) 2019 WAGO Kontakttechnik GmbH & Co. KG
+#-----------------------------------------------------------------------------#
+#-----------------------------------------------------------------------------#
+# Script:   docker init script
+#
+# Brief:    Startscript for dockerd and all associated processes.
+#
+# Author:   Fabian Schwamborn, WAGO Kontakttechnik GmbH & Co. KG
+#-----------------------------------------------------------------------------#
 
+DOCKER_IPTABLES_PATH="/opt/wago-docker/sbin/"
+EVENTDIR="/etc/config-tools/events/networking"
 
-function eval_result()
+DOCKER_PIDFILE="/var/run/docker.pid"
+DOCKER_IPT_NAMESPACE="WAGO_DOCKER_IPT"
+
+function firewall_hook_cleanup()
 {
-    if [[ "$?" == "0" ]]; then
-        echo -en "\\033[1;32m" 
-        echo -e "\\033[60G[SUCCESS]"
-    else
-        echo -en "\\033[1;31m" 
-        echo -e "\\033[60G[FAILED]"
+    if  ip netns list | grep -q "$DOCKER_IPT_NAMESPACE"; then
+        echo -n "cleaning up docker namespace..."
+        ip netns del "$DOCKER_IPT_NAMESPACE"
     fi
+}
 
-    echo -en "\\033[0;39m" 
+function firewall_hook_activate()
+{
+    firewall_hook_cleanup                                                  #clean up any leftovers
+    ip netns add "$DOCKER_IPT_NAMESPACE"                              #create namespace for iptable rule preservation
+
+}
+
+function firewall_hook_inactivate()
+{
+    firewall_hook_cleanup                                                   #remove docker firewall hook
+    test -e $EVENTDIR && run-parts -a config $EVENTDIR                       #clean up firewall
+
 }
 
 function do_docker_start()
 {
-
-    echo -n "Starting dockerd..."
-    start-stop-daemon -S --background --quiet --oknodo --pidfile /var/run/docker.pid --exec dockerd --
-    eval_result
+    echo "configuring network..."
+    firewall_hook_activate
+    echo -n "starting docker daemon..."
+    start-stop-daemon -S --background --quiet --oknodo --pidfile $DOCKER_PIDFILE --exec /usr/bin/env PATH="/"$DOCKER_IPTABLES_PATH":$PATH"  /usr/bin/dockerd --             #manipulate iptables-binary path!
 }
 
 function do_docker_stop()
 {
-    echo -n "Stopping dockerd..."
-    start-stop-daemon -K --quiet --oknodo --pidfile /var/run/docker.pid --
-    eval_result
+    echo "stopping dockerd..."
+    start-stop-daemon -K --quiet --oknodo --pidfile $DOCKER_PIDFILE --
+    firewall_hook_inactivate
+    
 }
 
 function usage()
@@ -40,21 +64,29 @@ function usage()
     echo "$0 usage: $0 [start|stop|restart]"
 }
 
-
 case $1 in
 
     start)      
-        do_docker_start
+        if test -r $DOCKER_PIDFILE && ps -p `cat $DOCKER_PIDFILE` > /dev/null 2>&1; then
+            echo "no action done - docker already running"
+            exit 1
+        else
+            do_docker_start
+            echo " done"
+        fi
         ;;
 
 	stop)
         do_docker_stop
+        echo " done"
         ;;
 
     restart)    
         do_docker_stop
-        sleep 1
+        sleep 3
+        echo -e "\ndocker stopped, starting again ..."
         do_docker_start
+        echo " done"
         ;;
     *)
         usage
diff --git a/projectroot/etc/config-tools/config_tool_lib b/projectroot/etc/config-tools/config_tool_lib
--- a/projectroot/etc/config-tools/config_tool_lib
+++ b/projectroot/etc/config-tools/config_tool_lib
@@ -27,6 +27,9 @@
 # Author:   OG:  WAGO Kontakttechnik GmbH & Co. KG
 #-----------------------------------------------------------------------------#
 
+#bash "include guard"
+if [[ ${CONFIG_TOOL_LIB_:-} != "config_tool_lib" ]]; then
+readonly CONFIG_TOOL_LIB_="config_tool_lib"
 
 #DO_PRINT_DBG=yes
 DO_PRINT_DBG=no
@@ -219,9 +222,9 @@ PLC_CONFIG_FILE="/etc/rts3s.cfg"
 MENU_LST="/boot/grub/menu.lst"
 INITTAB="/etc/inittab"
 LICENSE_INFORMATION_FILENAME="/etc/LICENSE"
-
-
-
+PASSWD_CHECK_BIN="/usr/bin/true"
+PASS_MIN_LENGTH=10
+IS_PASS_WEAK_CHECK="y"
 TRACE_FILENAME="/etc/config-tools/trace_debug.txt"
 
 CONFIG_TOOLS_PATH="/etc/config-tools/"
@@ -356,15 +359,14 @@ report_error()
     local SUPPRESS_LAST_ERROR=false
     SUPPRESS_LAST_ERROR=${3:+true}
     local RESULT=0
-    
 
     logger -t "${PREFIX}${0##*/} [$$] [Error]" -p user.err -- "$ERROR_TEXT"
-    
+
     if [[ "$SUPPRESS_LAST_ERROR" == false ]]; then
-    	SetLastError "$ERROR_TEXT"
+        SetLastError "$ERROR_TEXT"
     fi	
     RESULT=$?
-    
+
     if [ "$QUIET" -eq "0" ]; then
         echo_error "$ERROR_TEXT"
     fi
@@ -605,7 +607,7 @@ escape_json()
     local RESULT=0
 
     local JSON_TEXT=""
-    JSON_TEXT=$(printf '%s' "$TEXT" | php5 -r 'echo json_encode(file_get_contents("php://stdin"));')
+    JSON_TEXT=$(printf '%s' "$TEXT" | php -r 'echo json_encode(file_get_contents("php://stdin"));')
     RESULT=$?
     echo "$JSON_TEXT"
 
@@ -1049,11 +1051,13 @@ ReportError()
 #-----------------------------------------------------------------------------#
 SetLastError()
 {
-  local errorText=$*
+  local errorText="$*"
 
   print_dbg "SetLastError: ${errorText}"
-  # write error-text to file
-  flock -x $LAST_ERROR_FILENAME echo -e $errorText"\c" > $LAST_ERROR_FILENAME  
+
+  echo -n "$errorText" > "${LAST_ERROR_FILENAME}.tmp" &&
+    chgrp www "${LAST_ERROR_FILENAME}.tmp" &&
+    mv "${LAST_ERROR_FILENAME}.tmp" "${LAST_ERROR_FILENAME}"
 }
 
 # search for a specified parameter in the parameter-list
@@ -1276,15 +1280,15 @@ function SwitchBootPartition
 {
   status=$SUCCESS
 
-  /usr/sbin/${BOARD_ID}_switch_boot_partition.sh 
+  /usr/sbin/${BOARD_ID}_switch_boot_partition.sh
 
   if [ "$?" != $SUCCESS ]; then
     status=$SHELL_ERROR
     ReportError $status "(SwitchBootPartition)"
   fi
-  
+
   sync
-  
+
   return "$status"
 }
 
@@ -1382,22 +1386,74 @@ function GetTargetName
   # target name from sys-fs.
   if [[ -e "${board_variant}" ]]; then
 
-	product="$(cat ${board_variant})"
+    product="$(cat ${board_variant})"
 
   # legacy
   else
-	order="$(/etc/config-tools/get_typelabel_value ORDER)"
-	prefix="${order:0:3}"
-	order="${order:4:2}"
+    order="$(/etc/config-tools/get_typelabel_value ORDER)"
+    prefix="${order:0:3}"
+    order="${order:4:2}"
 
-	if [ "${order}" == "81" ]; then
-		product="PFC100"
-	elif [ "${order}" == "82" ]; then
-		product="PFC200"
-	elif [ "${prefix}" == "762" ]; then
-		product="TP600"
-	fi
+    if [ "${order}" == "81" ]; then
+      product="PFC100"
+    elif [ "${order}" == "82" ]; then
+      product="PFC200"
+    elif [ "${prefix}" == "762" ]; then
+      product="TP600"
+    fi
   fi
 
   echo "${product}"
 }
+
+function CheckEncryptionPassphrase
+{
+
+  local status=$SUCCESS
+  local password=$1
+  
+  CheckStringForASCII "$password"
+  if [ $status != $? ]; then
+    status=$INVALID_PARAMETER
+    ReportError $status $?
+    SetLastError $?
+  fi
+
+  # check password complexity only
+  $PASSWD_CHECK_BIN minLength=$PASS_MIN_LENGTH weakCheck="$IS_PASS_WEAK_CHECK" username=" " oldPasswd=" " \
+                    newPasswd="$password" confirmPasswd="$password" hostname=" "
+  if [ $? -ne 0 ]; then
+    status=$INVALID_PARAMETER
+    ReportError $status $?
+    SetLastError $?
+  fi
+
+  return $status
+}
+
+#### Begin D3I Implementation #######
+# Groups of ASCII special characters except ']' and '-'
+# We need a separate variable to avoid escaping
+# Notes:
+#       o ']' character must be the first one inside regex group
+#       o '-' character must either be the first or the last one
+# That's why they are placed within the main regex.
+
+function CheckStringForASCII
+{
+  local status=$SUCCESS
+  local inputString=$1
+  specialChars="\x20\x21\x22\x23\x24\x25\x26\x27\x28\x29\x2a\x2b\x2c\x2e\x2f\x3a\x3b\x3c\x3d\x3e\x3f\x40\x5b\x5c\x5e\x5f\x60\x7b\x7c\x7d\x7e"
+
+  if [[ ! "$inputString" =~ ^[]abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789$(echo -e $specialChars)-]*$ ]]; then
+    status=$INVALID_PARAMETER
+    ReportError $status "(password contains non-ASCII characters)"
+    SetLastError "Illegal characters used. Please only use letters (a-z, A-Z),\nnumbers and ASCII special characters: \n""] !\"#$%&'()*+,./:;<=>?@[\^_\`{|}~-"
+  fi
+
+  return $status
+}
+#### End D3I Implementation #######
+
+
+fi #if [[ ${CONFIG_TOOL_LIB_:-} != "config_tool_lib" ]]; then
diff --git a/projectroot/etc/config-tools/firmware_backup b/projectroot/etc/config-tools/firmware_backup
--- a/projectroot/etc/config-tools/firmware_backup
+++ b/projectroot/etc/config-tools/firmware_backup
@@ -23,46 +23,99 @@ fi
 
 statusFile="/var/www/wbm/firmware_backup_status"
 DEFAULTDESTDIR="/mnt/__destination_dir"
+DELETE_ALL_BACKUP_FILES=1
 
 function SavePartition
 {
 
-  local mode=$1 # 'rootfs' or 'codesys'
-  local filename=$2
-  local destinationDir=$3
-  local callMode=${4:-""}
+  local mode="$1" # 'rootfs' or 'codesys'
+  local filename="$2"
+  local destinationDir="$3"
+  local callMode="${4:-}"
 
   local status=$SUCCESS
 
   if [[ "$callMode" == "cbm" ]]; then
     # provide no status file -> display progress bar in terminal
-    /usr/sbin/${BOARD_ID}_save_partition.sh $mode $filename $destinationDir
+    /usr/sbin/${BOARD_ID}_save_partition.sh "$mode" "$filename" "$destinationDir"
     status=$?
   else
-     /usr/sbin/${BOARD_ID}_save_partition.sh $mode $filename $destinationDir $statusFile
+     /usr/sbin/${BOARD_ID}_save_partition.sh "$mode" "$filename" "$destinationDir" "$statusFile"
     status=$?
-  fi
-
+    # Provide encryption passphrase via filedescriptor 5 to not show up in "ps"
+  fi 5<< EOF
+${encPassphrase}
+EOF
 
   return $status
 }
 
 function do_cleanup
 {
+  # we have to check the used space error here because
+  # if tar or gpg (encryption) process failed in function "SavePartition"
+  # the script "pfcXXX_save_partition.sh" "exits" without checking "used space error"
+  # and we also have to "check" the backup_settings
+  case $status in
+     $SUCCESS) 
+     ;;
+     *)
+     usedSpace=$(df | awk -v pattern=$destinationDir\$ 'match($0,pattern) {print $5}')
+     if [[ "$usedSpace" == "100%" ]]; then
+       status=$NOT_ENOUGH_SPACE_ERROR
+       SetLastError "Not enough space on target. Could not generate backup files."
+     else
+       status=$SHELL_ERROR
+       SetLastError "Could not generate backup files. Please check your backup target."
+     fi
+     initPartition 0
+     ;;
+  esac
+
   # check if destination directory was mounted and if so, unmount it
   if mount | grep -q "${DEFAULTDESTDIR}"; then
     umount "${DEFAULTDESTDIR}"
   fi
 
-  # check if directory used for mounting is existing and if so, remove it
-  if [[ -d "${DEFAULTDESTDIR}" ]]; then
-    rm -rf "${DEFAULTDESTDIR}"
-  fi
-
   # remove status file
-  rm $statusFile > /dev/null 2> /dev/null
+  rm -rf "${DEFAULTDESTDIR}"
+  rm -f "$statusFile" /tmp/ignored_file_list.txt
 }
 
+function initPartition
+{
+  local codeSysResFile="${destinationDir}/${CODESYS_FILENAME}.tgz$encExt"
+  local systemResFile="${destinationDir}/${SYSTEM_FILENAME}.tgz$encExt"
+  local settingsResFile="${destinationDir}/${SETTINGS_FILENAME}$encExt"
+  local autoAttr="auto_"
+  local deleteAll=$1
+ 
+  if [ "$deleteAll" = "$DELETE_ALL_BACKUP_FILES" ] || [ "$packageCodesys" = "1" ]; then
+    rm -f $codeSysResFile
+  fi
+  if [ "$deleteAll" = "$DELETE_ALL_BACKUP_FILES" ] || [ "$packageSystem" = "1" ]; then
+    rm -f $systemResFile
+  fi
+  if [ "$deleteAll" = "$DELETE_ALL_BACKUP_FILES" ] || [ "$packageSettings" = "1" ]; then
+    rm -f $settingsResFile
+  fi
+  
+  # delete all (?) plaintext auto update files when generating new backups?
+  # encrypted auto files were not generated (we prevent this)
+  
+  # in case of an error during backup process delete all generated auto backup files
+  if [ "$deleteAll" != "$DELETE_ALL_BACKUP_FILES" ] && [ "$activateAutoUpdate" = 1 ]; then
+    if [ "$packageCodesys" = "1" ]; then
+      rm -f ${destinationDir}/$autoAttr${CODESYS_FILENAME}.tgz
+    fi
+    if [ "$packageSystem" = "1" ]; then
+      rm -f ${destinationDir}/$autoAttr${SYSTEM_FILENAME}.tgz
+    fi
+    if [ "$packageSettings" = "1" ]; then
+      rm -f ${destinationDir}/$autoAttr${SETTINGS_FILENAME}
+    fi
+  fi
+}
 
 #-------------- main-programm ------------------------#
 
@@ -75,9 +128,9 @@ if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
   echo
   echo "* Process backup of firmware data *"
   echo
-  echo "Usage: firmware_backup < package-settings=value package-system=value package-codesys=value device-medium=value > [ auto-update=value ] [ download-dir=value ]"
+  echo "Usage: firmware_backup < package-settings=value package-system=value package-codesys=value device-medium=value > [ auto-update=value ] [ download-dir=value ] [ passphrase=value ]"
   echo
-  echo "package-settings, package-system, package-codesys: 1, if package should be saved, else parameter can be absent"
+  echo "package-settings, package-system, package-codesys: 1 to save package. May be omitted otherwise"
 
   mediumCnt=1
   mediumName=$(/etc/config-tools/get_filesystem_data medium-by-index $mediumCnt)
@@ -97,8 +150,9 @@ if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
 
   echo "network"
 
-  echo "auto-update: 1, if auto update should be activated, else it can fall away"
+  echo "auto-update: 1 to activate auto update. May be omitted otherwise"
   echo "download-dir: directory to save the backup file if the device medium is network"
+  echo "passphrase: password for backup encryption"
   exit $status
 fi
 
@@ -107,6 +161,8 @@ packageAll=`GetParameterValue package-all $*`
 packageCodesys=`GetParameterValue package-codesys $*`
 packageSettings=`GetParameterValue package-settings $*`
 packageSystem=`GetParameterValue package-system $*`
+# FIXME: Encryption password on the command line (sigh)
+encPassphrase=`GetParameterValue passphrase $*`
 callMode=$(GetParameterValue callMode $*)
 #echo "packageAll:"$packageAll "packageCodesys:"$packageCodesys "packageSettings:"$packageSettings "packageSystem:"$packageSystem
 
@@ -120,10 +176,32 @@ if [ -n "$packageAll" ] && [ "$packageAll" = "1" ]; then
   packageSystem=1
 fi
 
+if [ -n "$encPassphrase" ]; then
+  do_encrypt="yes"
+  # Provide encryption passphrase via filedescriptor 5 to not show up in "ps"
+  # Filedescriptor 3 and 4 are occupied by "SuppressMessageOutput"
+  ENCRYPT="openssl enc -aes-256-cfb -md sha512 -pass fd:5"
+  encExt=".enc"
+else
+  do_encrypt="no"
+  ENCRYPT=cat
+  encExt=""
+fi
+export ENCRYPT encExt do_encrypt
+
 # check input parameter
 if [ "$packageCodesys" != "1" ] && [ "$packageSettings" != "1" ] && [ "$packageSystem" != "1" ]; then
   SetLastError "No package selected"
   exit $INVALID_PARAMETER
+fi
+
+# check input parameter passphrase
+if [ "$do_encrypt" = yes ]; then
+    CheckEncryptionPassphrase "$encPassphrase"
+    if [ $? -ne 0 ]; then
+      SetLastError "weak/invalid encryption passphrase"
+      exit $INVALID_PARAMETER
+    fi
 fi
 
 # check input for device medium; must be included in DEVICE_MEDIA configuration or network 
@@ -154,13 +232,19 @@ if [ "$INTERNAL_FLASH_NAND" = "$deviceMedium" ]; then
   exit $INVALID_PARAMETER
 fi
 
-echo "Start firmware backup" > $statusFile
-
 # set filename appendix for auto update feature if requested
 autoUpdateAppendix=""
 if [ "$activateAutoUpdate" = 1 ]; then
-  autoUpdateAppendix="auto_"
+  if [ "$do_encrypt" = no ]; then
+    autoUpdateAppendix="auto_"
+  else
+    status=$EXECUTABLE_ERROR
+    SetLastError "No auto update feature with encrypted backups."
+    ReportError $status "No auto update feature with encrypted backups."
+  fi
 fi
+
+echo "Start firmware backup" > $statusFile
 
 # destination device is network -> an input parameter must specify the directory for saving the backup file
 if [ "$deviceMedium" = "$NETWORK" ]; then
@@ -218,33 +302,49 @@ else
       status=$?
     fi
   fi
+  
+  # We have to delete the plaintext files in destination partition if encrypted mode is active.
+  # In this case we could delete all plaintext files before backup.
+  # If encryption is active there schould no plaintext backup file in destination partition !!!!  
+  initPartition "$DELETE_ALL_BACKUP_FILES"
 fi
 
 # now we should have any directory to save our data and can continue with generating it
 if [ "$status" = "$SUCCESS" ]; then
 
   # settings must be saved -> use special script to create settings file and move it directly to destination (device or directory for download)
-  if [ "$packageSettings" = "1" ]; then 
+  if [ "$packageSettings" = "1" ]; then
+    settingsBackupFile="${destinationDir}/${autoUpdateAppendix}${SETTINGS_FILENAME}${encExt}"
     #echo "save settings destinationDir:${destinationDir}"
-    echo "Saving settings" > $statusFile
+    echo "Saving settings" > "$statusFile"
 
-    /etc/config-tools/settings_backup save ${destinationDir}/${autoUpdateAppendix}${SETTINGS_FILENAME} #> /dev/null 2> /dev/null
-    if [ "$?" != $SUCCESS ]; then
+    /etc/config-tools/settings_backup save "${settingsBackupFile}"
+    if [ "$?" != "$SUCCESS" ]; then
       status=$EXECUTABLE_ERROR
       ReportError $status "(settings_backup)"
     fi
+
+    # Provide encryption passphrase via filedescriptor 5 to not show up in "ps"
+    if [ "${do_encrypt}" = 'yes' ]; then
+      $ENCRYPT <"${settingsBackupFile}" >"${settingsBackupFile}.tmp" \
+        && mv "${settingsBackupFile}.tmp" "${settingsBackupFile}" \
+        && sync
+    fi 5<< EOF
+${encPassphrase}
+EOF
+
   fi
 
   # complete codesys image must be saved -> create image, zip it and copy it to destination
   if [ "$status" = "$SUCCESS" ] && [ "$packageCodesys" = "1" ]; then
     #echo "save codesys"
-    SavePartition "codesys" ${autoUpdateAppendix}${CODESYS_FILENAME} $destinationDir $callMode
+    SavePartition "codesys" "${autoUpdateAppendix}${CODESYS_FILENAME}" "$destinationDir" "$callMode"
     status=$?
   fi
 
   # complete system image must be saved -> create image, zip it and copy it to destination
   if [ "$status" = "$SUCCESS" ] && [ "$packageSystem" = "1" ]; then
-    SavePartition "rootfs" ${autoUpdateAppendix}${SYSTEM_FILENAME} $destinationDir $callMode
+    SavePartition "rootfs" "${autoUpdateAppendix}${SYSTEM_FILENAME}" "$destinationDir" "$callMode"
     status=$?
   fi
 
diff --git a/projectroot/etc/init.d/check_rtc b/projectroot/etc/init.d/check_rtc
--- a/projectroot/etc/init.d/check_rtc
+++ b/projectroot/etc/init.d/check_rtc
@@ -18,6 +18,8 @@
 #-----------------------------------------------------------------------------#
 
 THISFILE="$0"
+EARLYLOG_DIR="/var"
+EARLYLOG_FILE="wagoearlylog.log"
 
 # Function to print usage to stdout.
 #
@@ -66,6 +68,7 @@ set_build_date()
 # Function to check RTC status.
 #
 # Return: 0 on success, unequal to 0 otherwise
+#-----------------------------------------------------------------------------#
 check_rtc()
 {
     local result=0
@@ -77,7 +80,12 @@ check_rtc()
           hwclock -w &&
           echo "Warning: RTC failure. Set date to '$(/usr/bin/date -I)'" 1>&2
         result=$?
-        date "+%a %b %d %Y %X.000000 0x8000000C init: S" >>"/root/wagoearlylog.log"
+        mkdir -p "$EARLYLOG_DIR"
+        if [[ $? -ne 0 ]]; then
+            echo "Failed to create log directory for early log messages \"$EARLYLOG_DIR\"" 1>&2
+        else
+            date "+%a %b %d %Y %X.000000 0x8000000C init: S" >>"$EARLYLOG_DIR/$EARLYLOG_FILE"
+        fi
     else
         echo "RTC ok: $hwclock_datestring"
     fi
@@ -88,6 +96,7 @@ check_rtc()
 # Function to reset system time to build date.
 #
 # Return: 0 on success, unequal to 0 otherwise
+#-----------------------------------------------------------------------------#
 reset_date()
 {
     set_build_date &&
diff --git a/projectroot/etc/init.d/link_devices b/projectroot/etc/init.d/link_devices
--- a/projectroot/etc/init.d/link_devices
+++ b/projectroot/etc/init.d/link_devices
@@ -9,6 +9,79 @@
 DEVS_TO_LINK="/etc/specific/.devs_to_link"
 DEV_SEARCH_PATH="/sys/devices/"
 
+check_unnamed()
+{
+    local extract_result=$1
+    local name="$2"
+    local device="$3"
+
+    if [[ $extract_result -ne 0 || -z "$name" ]]; then
+        echo "unnamed_$device"
+    else
+        echo "$name"
+    fi
+
+    return 0
+}
+
+extract_nand_label()
+{
+    local ubi_device="$1"
+
+    local name=""
+    name="$(cat "/sys/class/ubi/$ubi_device/name")"
+    check_unnamed $? "$name" "$ubi_device"
+
+    return 0
+}
+
+extract_emmc_label()
+{
+    local partition_device="$1"
+
+    local name=""
+    name="$(blkid "/dev/$partition_device" | sed -n 's/.*LABEL=\"\(\S\+\)\".*/\1/p')"
+    check_unnamed $? "$name" "$partition_device"
+
+    return 0
+}
+
+
+if [[ -c "/dev/mtd8" ]]; then
+    detach_ubi=false
+    if [[ ! -e "/sys/class/ubi/ubi0_0" ]]; then
+        /sbin/ubiattach --mtdn=8 &>/dev/null
+        detach_ubi=true
+    fi
+    # static partitions for systems with internal flash nand
+    PARTITION_NAND_ROOTFS1_DEV_NAME="ubi0_0"
+    PARTITION_NAND_ROOTFS1_LINK_NAME="/dev/partition_$(extract_nand_label "$PARTITION_NAND_ROOTFS1_DEV_NAME")"
+    PARTITION_NAND_ROOTFS2_DEV_NAME="ubi0_2"
+    PARTITION_NAND_ROOTFS2_LINK_NAME="/dev/partition_$(extract_nand_label "$PARTITION_NAND_ROOTFS2_DEV_NAME")"
+    PARTITION_NAND_HOME1_DEV_NAME="ubi0_1"
+    PARTITION_NAND_HOME1_LINK_NAME="/dev/partition_$(extract_nand_label "$PARTITION_NAND_HOME1_DEV_NAME")"
+
+    if $detach_ubi; then
+        /sbin/ubidetach --mtdn=8 &>/dev/null
+    fi
+else
+    # static partitions for systems with internal flash emmc
+    PARTITION_EMMC_BOOT_DEV_NAME="mmcblk1p1"
+    PARTITION_EMMC_BOOT_LINK_NAME="/dev/partition_$(extract_emmc_label "$PARTITION_EMMC_BOOT_DEV_NAME")"
+    PARTITION_EMMC_ROOTFS1_DEV_NAME="mmcblk1p7"
+    PARTITION_EMMC_ROOTFS1_LINK_NAME="/dev/partition_$(extract_emmc_label "$PARTITION_EMMC_ROOTFS1_DEV_NAME")"
+    PARTITION_EMMC_ROOTFS2_DEV_NAME="mmcblk1p10"
+    PARTITION_EMMC_ROOTFS2_LINK_NAME="/dev/partition_$(extract_emmc_label "$PARTITION_EMMC_ROOTFS2_DEV_NAME")"
+    PARTITION_EMMC_HOME1_DEV_NAME="mmcblk1p8"
+    PARTITION_EMMC_HOME1_LINK_NAME="/dev/partition_$(extract_emmc_label "$PARTITION_EMMC_HOME1_DEV_NAME")"
+    PARTITION_EMMC_HOME2_DEV_NAME="mmcblk1p9"
+    PARTITION_EMMC_HOME2_LINK_NAME="/dev/partition_$(extract_emmc_label "$PARTITION_EMMC_HOME2_DEV_NAME")"
+    PARTITION_EMMC_LOG_DEV_NAME="mmcblk1p5"
+    PARTITION_EMMC_LOG_LINK_NAME="/dev/partition_$(extract_emmc_label "$PARTITION_EMMC_LOG_DEV_NAME")"
+    PARTITION_EMMC_SETTINGS_DEV_NAME="mmcblk1p6"
+    PARTITION_EMMC_SETTINGS_LINK_NAME="/dev/partition_$(extract_emmc_label "$PARTITION_EMMC_SETTINGS_DEV_NAME")"
+fi
+
 # get configured kbus uart from sys-fs
 KBUS_TTY_PFCXXX_DEV_NAME="$(cat /sys/class/wago/system/kbus_tty_device_name)"
 KBUS_TTY_PFCXXX_LINK_NAME="/dev/ttyKbus"
@@ -57,47 +130,60 @@ fi
 case $1 in
 
   start)
-	# if device kbus0 exist the kernel supports KBus so from the userspace we can check if kbus0 exists
-	if [ -e /dev/kbus0 ]
-	then
-        	if [ -c "/dev/${KBUS_TTY_PFCXXX_DEV_NAME}" ]; then
-        	        ln -s /dev/${KBUS_TTY_PFCXXX_DEV_NAME} ${KBUS_TTY_PFCXXX_LINK_NAME}
-	        else
-	                echo "ERROR: could not set ${KBUS_TTY_PFCXXX_LINK_NAME}, kbus will not be active"
-        	fi
-	fi
+        # if device kbus0 exist the kernel supports KBus so from the userspace we can check if kbus0 exists
+        if [ -e /dev/kbus0 ]; then
+                if [ -c "/dev/${KBUS_TTY_PFCXXX_DEV_NAME}" ]; then
+                        ln -s /dev/${KBUS_TTY_PFCXXX_DEV_NAME} "${KBUS_TTY_PFCXXX_LINK_NAME}"
+                else
+                        echo "ERROR: could not set ${KBUS_TTY_PFCXXX_LINK_NAME}, kbus will not be active"
+                fi
+        fi
 
         if [ -c "/dev/${SERIAL_TTY_PFCXXX_DEV_NAME}" ]; then
-                ln -s /dev/${SERIAL_TTY_PFCXXX_DEV_NAME} ${SERIAL_TTY_PFCXXX_LINK_NAME}
+                ln -s /dev/${SERIAL_TTY_PFCXXX_DEV_NAME} "${SERIAL_TTY_PFCXXX_LINK_NAME}"
         else
                 echo "ERROR: could not set ${SERIAL_TTY_PFCXXX_LINK_NAME}, getty will fail"
         fi
 
         if [ -c "/dev/${SERVICE_TTY_PFCXXX_DEV_NAME}" ]; then
-                ln -s /dev/${SERVICE_TTY_PFCXXX_DEV_NAME} ${SERVICE_TTY_PFCXXX_LINK_NAME}
+                ln -s /dev/${SERVICE_TTY_PFCXXX_DEV_NAME} "${SERVICE_TTY_PFCXXX_LINK_NAME}"
         else
                 echo "ERROR: could not set ${SERVICE_TTY_PFCXXX_LINK_NAME}, getty will fail"
         fi
 
-        ln -s /dev/${GSM_MODEM_TTY_PFCXXX_DEV_NAME} ${GSM_MODEM_TTY_PFCXXX_LINK_NAME}
+        ln -s /dev/${GSM_MODEM_TTY_PFCXXX_DEV_NAME} "${GSM_MODEM_TTY_PFCXXX_LINK_NAME}"
 
         for path in "${device_paths[@]}"; do
                 ln -s ${path} /dev/
         done
-                
+
         # ----- led naming -----
         # create folder 
         if [ ! -d "${LED_DEST_PATH}" ]; then
-                mkdir ${LED_DEST_PATH}
+                mkdir "${LED_DEST_PATH}"
         fi
-        
+
         # link led names 
         if [ -d "${LED_DEST_PATH}" ]; then
-                ln -s ${LED_SRC_PATH}* ${LED_DEST_PATH}
+                ln -s ${LED_SRC_PATH}* "${LED_DEST_PATH}"
         else
                 echo "ERROR: could not set ${LED_DEST_PATH}, leds will not work"
         fi
-        
+
+        # ----- internal flash partitions -----
+        if [[ -c "/dev/mtd8" ]]; then
+                ln -s /dev/${PARTITION_NAND_ROOTFS1_DEV_NAME}    "${PARTITION_NAND_ROOTFS1_LINK_NAME}"
+                ln -s /dev/${PARTITION_NAND_ROOTFS2_DEV_NAME}    "${PARTITION_NAND_ROOTFS2_LINK_NAME}"
+                ln -s /dev/${PARTITION_NAND_HOME1_DEV_NAME}      "${PARTITION_NAND_HOME1_LINK_NAME}"
+        else
+                ln -s /dev/${PARTITION_EMMC_BOOT_DEV_NAME}       "${PARTITION_EMMC_BOOT_LINK_NAME}"
+                ln -s /dev/${PARTITION_EMMC_ROOTFS1_DEV_NAME}    "${PARTITION_EMMC_ROOTFS1_LINK_NAME}"
+                ln -s /dev/${PARTITION_EMMC_ROOTFS2_DEV_NAME}    "${PARTITION_EMMC_ROOTFS2_LINK_NAME}"
+                ln -s /dev/${PARTITION_EMMC_HOME1_DEV_NAME}      "${PARTITION_EMMC_HOME1_LINK_NAME}"
+                ln -s /dev/${PARTITION_EMMC_HOME2_DEV_NAME}      "${PARTITION_EMMC_HOME2_LINK_NAME}"
+                ln -s /dev/${PARTITION_EMMC_LOG_DEV_NAME}        "${PARTITION_EMMC_LOG_LINK_NAME}"
+                ln -s /dev/${PARTITION_EMMC_SETTINGS_DEV_NAME}   "${PARTITION_EMMC_SETTINGS_LINK_NAME}"
+        fi
   ;;
   stop)
   ;;
