Update 03.07.14-FW19
Signed-off-by: Thomas Brandt <Thomas.Brandt@wago.com>

diff --git a/local_src/netconfd/root/etc/init.d/netconfd b/local_src/netconfd/root/etc/init.d/netconfd
--- a/local_src/netconfd/root/etc/init.d/netconfd
+++ b/local_src/netconfd/root/etc/init.d/netconfd
@@ -10,20 +10,74 @@ RUNDIR="/var/run/netconfd"
 PIDFILE="netconfd.pid"
 PATHPIDFILE=$RUNDIR/$PIDFILE
 NETCONFD="/usr/bin/netconfd"
-STARTCMD="$NETCONFD --daemon --rundir=$RUNDIR --pidfile=$PIDFILE --loglevel=debug"
+STARTCMD="$NETCONFD --daemon --rundir=$RUNDIR --pidfile=$PIDFILE --loglevel=error"
 
 set -e
 
-function stop_netconfd {
-    start-stop-daemon --stop --pidfile $PATHPIDFILE --retry=TERM/20/KILL/10 --oknodo --exec $NETCONFD
+
+function Log() {
+    [[ $# -gt 0 ]] && logger -t "netconfd init script" "$1"
+}
+
+function modify_start_cmd() {
+  # Check if FW update is running its first boot,
+  # in this case we must keep the ethernet ports down
+  # in order to prevent default bridge configuration (all ports switched)
+  source "/usr/sbin/fwupdate_basic_defines"
+  if [ -f "${WAGO_FW_UPDATE_FIRST_BOOT_MARKER}" ]; then
+    Log "FW update detected: netconfd is starting with all ports down!"
+    STARTCMD="$STARTCMD --startup-ports-down"
+  fi
+}
+
+function is_pid_alive() {
+    if [ -n "$1" ] && ps -p $1 >/dev/null; then
+        return 0
+    fi
+    return 1
+}
+
+function stop_netconfd() {
+    if [ ! -f "$PATHPIDFILE" ]; then
+        Log "Pid file $PATHPIDFILE does not exist. Doing nothing!"
+        return 0
+    fi
+
+    local pid="$(cat $PATHPIDFILE)"
+
+    if is_pid_alive $pid; then
+        Log "Terminate pid $pid"
+        kill $pid
+        local timeout=30
+        while [[ $timeout > 0 ]]; do
+            is_pid_alive $pid || break
+            : $((timeout--))
+            sleep 1
+        done
+        if is_pid_alive $pid; then
+            kill -9 $pid
+            Log "Failed to terminate $pid, send kill"
+        fi
+    else
+        Log "pid $pid is already dead"
+    fi
     /usr/bin/rm -f $PATHPIDFILE
+    return 0
+}
+
+function start_netconfd() {
+  # First action is to modify the start command based on the current environment
+  modify_start_cmd
+  
+  $STARTCMD
+  
+  echo "done"
 }
 
 
 case $1 in
 start)
-    $STARTCMD
-    echo "done"
+    start_netconfd
     ;;
 
 stop)
@@ -33,11 +87,11 @@ stop)
 
 restart)
     echo "Restart network configuration daemon"
-    stop_netconfd
-    $STARTCMD
-    echo "done"
+    stop_netconfd || : # ignore failing stop result
+		start_netconfd
     ;;
 
 *)
-    echo "Usage $0 start | stop | restart"
+    echo "Usage: $0 start | stop | restart"
+    ;;
 esac
diff --git a/projectroot/etc/init.d/lighttpd b/projectroot/etc/init.d/lighttpd
--- a/projectroot/etc/init.d/lighttpd
+++ b/projectroot/etc/init.d/lighttpd
@@ -1,32 +1,95 @@
-#!/bin/sh
+#!/bin/bash
+
+# This Source Code Form is subject to the terms of the Mozilla Public
+# License, v. 2.0. If a copy of the MPL was not distributed with this
+# file, You can obtain one at http://mozilla.org/MPL/2.0/.
+#
+# Copyright (c) 2021 WAGO Kontakttechnik GmbH & Co. KG
 
 #
-# lighttpd
+# lighttpd start script
 #
-PATH=/usr/bin:/usr/sbin:/bin:/sbin
 
 PREFIX="lighttpd: "
 LIGHTTPD="/usr/sbin/lighttpd"
+LIGHTTPD_PROC="lighttpd"
+LIGHTTPD_PIDFILE="/var/run/lighttpd.pid"
 LIGHTTPD_CONF="/etc/lighttpd/lighttpd.conf"
+LIGHTTPD_LOGDIR="/var/log/lighttpd"
+LIGHTTPD_PHP_SESSION_DIR="/var/run/php/sessions"
+START_STOP_DAEMON="/sbin/start-stop-daemon"
+
+# Utility function to store process id after service startup
+store_pidfile()
+{
+	# Determine the pid of lighttpd by filter out own pid.
+	# One will be this script itself because it's named equally.
+	local own_pid="$BASHPID"
+	local lighttpd_pids
+	lighttpd_pids="$(pidof "${LIGHTTPD_PROC}")"
+	for pid in $lighttpd_pids; do
+		if [[ "$pid" != "$own_pid" ]]; then
+			echo -n "$pid" > "${LIGHTTPD_PIDFILE}"
+		fi
+	done
+}
+
+# Utility function to remove PID-File after stopping the service
+remove_pidfile()
+{
+	rm -f "${LIGHTTPD_PIDFILE}"
+}
+
+# Utility function to create a directory and assign appropriate 
+# permissions as required by the service
+create_directry_if_needed()
+{
+	local directory="$1"
+	if [ ! -d "${directory}" ]; then
+		mkdir -p "${directory}"
+		chmod 700 "${directory}"
+		chown www:www "${directory}"
+    fi
+}
+
+# Start the service 
+start()
+{
+	create_directry_if_needed "${LIGHTTPD_LOGDIR}"
+	create_directry_if_needed "${LIGHTTPD_PHP_SESSION_DIR}"
+	$START_STOP_DAEMON --quiet --start --exec "${LIGHTTPD}" -- -f "${LIGHTTPD_CONF}"
+	return $?
+}
+
+# Stop the service 
+stop()
+{
+    $START_STOP_DAEMON --quiet --stop --oknodo --exec "${LIGHTTPD}"
+	return $?
+}
+
+# Reload configuration of the service
+reload()
+{
+	local retval=-1
+	store_pidfile
+	if $START_STOP_DAEMON --stop --signal SIGINT --oknodo --quiet --pidfile "${LIGHTTPD_PIDFILE}" --exec "${LIGHTTPD}"; then
+		while start-stop-daemon --stop -t --quiet --pidfile "${LIGHTTPD_PIDFILE}" --exec "${LIGHTTPD}"; do
+			usleep 10000;
+		done
+		if start; then
+			retval=0
+		fi
+	fi
+    remove_pidfile
+	return $retval;	
+}
 
 case $1 in
 
 	start)
 		echo "${PREFIX}starting"
-
-		if [ \! -d /var/log/lighttpd ]; then
-			mkdir -p /var/log/lighttpd
-			chmod 700 /var/log/lighttpd
-			chown www:www /var/log/lighttpd
-		fi
-
-		if [ \! -d /var/run/php/sessions ]; then
-			mkdir -p /var/run/php/sessions
-			chmod 700 /var/run/php/sessions
-			chown www:www /var/run/php/sessions
-		fi
-
-		if start-stop-daemon --start --quiet --oknodo --exec ${LIGHTTPD} -- -f ${LIGHTTPD_CONF}; then
+		if start; then
 			echo "${PREFIX}done"
 		else
 			echo "${PREFIX}error, could not start server"
@@ -35,16 +98,24 @@ case $1 in
 
 	stop)
 		echo "${PREFIX}stopping"
-		
-		if start-stop-daemon --stop --quiet --oknodo --exec ${LIGHTTPD}; then
+		if stop; then
 			echo "${PREFIX}done"
 		else
 			echo "${PREFIX}error, could not stop server"
 		fi
 		;;
 
+	reload)
+		echo "${PREFIX}reloading"
+		if reload; then
+			echo "${PREFIX}done"
+		else
+			echo "${PREFIX}error, could not reload server"
+		fi
+		;;
+
 	*)
-		echo "${PREFIX}usage: ${0} [start|stop]"
+		echo "${PREFIX}usage: ${0} [start|stop|reload]"
 		exit 1
 		;;
 
diff --git a/projectroot/etc/init.d/networking-finish b/projectroot/etc/init.d/networking-finish
--- a/projectroot/etc/init.d/networking-finish
+++ b/projectroot/etc/init.d/networking-finish
@@ -58,8 +58,12 @@ function get_next_macs
 
 function marvell_update_eeprom
 {
-    log "update switch eeprom"
-    /sbin/pfcXXX_config_network_switch_eeprom.sh /proc/device-tree/ocp/ethernet@4a100000/mdio@4a101000/switch@0/eeprom
+   /sbin/pfcXXX_config_network_switch_eeprom.sh /sys/firmware/devicetree/base/ocp/interconnect@4a000000/segment@0/target-module@100000/ethernet@0/mdio@1000/switch@0/eeprom
+   if [[ "$?" != "0" ]] ; then
+        log "update switch eeprom failed"
+   else
+        log "update switch eeprom"
+   fi
 }
 
 function marvell_configure_atu
@@ -74,6 +78,7 @@ function marvell_configure_atu
     declare -a macs
     get_next_macs "$macaddr" $mac_addr_count
 
+    swconfig dev switch0 set port_fdb_add "${macs[0]},6,0"
     for mac in "${macs[@]}"; do
         swconfig dev switch0 set port_fdb_add "${mac},6,0"
     done
