Update 03.06.09-FW18

diff --git a/patches/ipwatchd-1.2.1/adapt-init-script.patch b/patches/ipwatchd-1.2.1/adapt-init-script.patch
--- a/patches/ipwatchd-1.2.1/adapt-init-script.patch
+++ b/patches/ipwatchd-1.2.1/adapt-init-script.patch
@@ -1,8 +1,8 @@
 Index: ipwatchd-1.2.1/src/scripts/ipwatchd
 ===================================================================
---- ipwatchd-1.2.1.orig/src/scripts/ipwatchd	2011-07-24 14:39:03.000000000 +0000
-+++ ipwatchd-1.2.1/src/scripts/ipwatchd	2014-06-27 12:22:00.002321717 +0000
-@@ -1,56 +1,35 @@
+--- ipwatchd-1.2.1.orig/src/scripts/ipwatchd
++++ ipwatchd-1.2.1/src/scripts/ipwatchd
+@@ -1,117 +1,89 @@
  #! /bin/sh
 -
 -### BEGIN INIT INFO
@@ -51,8 +51,8 @@ Index: ipwatchd-1.2.1/src/scripts/ipwatchd
  #
  # Function that starts the daemon/service
  #
- do_start()
- {
+-do_start()
+-{
 -	# Return
 -	#   0 if daemon has been started
 -	#   1 if daemon was already running
@@ -62,19 +62,20 @@ Index: ipwatchd-1.2.1/src/scripts/ipwatchd
 -	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- \
 -		$DAEMON_ARGS \
 -		|| return 2
++do_start() {
 +        # Return
 +        #   0 if daemon has been started
 +        #   1 if daemon was already running
 +        #   2 if daemon could not be started
-+        start-stop-daemon --quiet --exec $DAEMON --test -K && return 1
++        start-stop-daemon --quiet --exec $DAEMON --pidfile $PIDFILE --test -K && return 1
 +        start-stop-daemon --quiet --exec $DAEMON -S -- $DAEMON_ARGS || return 2
  }
  
  #
-@@ -58,60 +37,79 @@
+ # Function that stops the daemon/service
  #
- do_stop()
- {
+-do_stop()
+-{
 -	# Return
 -	#   0 if daemon has been stopped
 -	#   1 if daemon was already stopped
@@ -85,42 +86,22 @@ Index: ipwatchd-1.2.1/src/scripts/ipwatchd
 -	[ "$RETVAL" = 2 ] && return 2
 -	rm -f $PIDFILE
 -	return "$RETVAL"
++do_stop() {
 +        # Return
 +        #   0 if daemon has been stopped
 +        #   1 if daemon was already stopped
 +        #   2 if daemon could not be stopped
 +        #   other if a failure occurred
-+        start-stop-daemon --quiet --pidfile $PIDFILE -K
++        start-stop-daemon -s 9 --quiet --pidfile $PIDFILE -K
++        if kill -0 $(cat $PIDFILE) 2> /dev/null; then sleep 1; fi;
 +        RETVAL="$?"
 +        [ "$RETVAL" = 2 ] && return 2
 +        rm -f $PIDFILE
 +        return "$RETVAL"
-+}
-+
-+# On PFC200 change /etc/ipwatchd.conf according to DSA configuration.
-+set_config()
-+{
-+	local dsamode
-+	if [ -x /etc/config-tools/get_dsa_mode ]; then
-+		# Ok. We have config tools present. If required, change config file accordingly.
-+		dsamode=$(/etc/config-tools/get_dsa_mode)
-+		grep -q "^# iface br1 active" $CONF_FILE
-+		if [ "$?" != "$dsamode" ]; then
-+			# change config file because dsa mode does not match
-+			if [ "$dsamode" = "0" ]; then
-+				awk ' /iface br1/ {print "# iface br1 active"; next} {print}' $CONF_FILE > $CONF_FILE.new
-+			else
-+				awk ' /iface br1/ {print "iface br1 active"; next} {print}' $CONF_FILE > $CONF_FILE.new
-+			fi
-+			sync
-+			mv $CONF_FILE.new $CONF_FILE
-+			sync
-+		fi
-+	fi
  }
  
  case "$1" in
-   start)
+-  start)
 -	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
 -	do_start
 -	case "$?" in
@@ -128,15 +109,7 @@ Index: ipwatchd-1.2.1/src/scripts/ipwatchd
 -		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
 -	esac
 -	;;
-+	set_config
-+        do_start
-+        case "$?" in
-+                0) [ "$VERBOSE" != no ] && echo "Started $NAME, $DESC" ;;
-+                1) [ "$VERBOSE" != no ] && echo "$NAME already running" ;;
-+                2) [ "$VERBOSE" != no ] && echo "Start of $NAME failed" ;;
-+        esac
-+        ;;
-   stop)
+-  stop)
 -	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
 -	do_stop
 -	case "$?" in
@@ -147,14 +120,7 @@ Index: ipwatchd-1.2.1/src/scripts/ipwatchd
 -  status)
 -       status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
 -       ;;
-+        do_stop
-+        case "$?" in
-+                0) [ "$VERBOSE" != no ] && echo "Stopped $NAME" ;;
-+                1) [ "$VERBOSE" != no ] && echo "$NAME already stopped" ;;
-+                2) [ "$VERBOSE" != no ] && echo "$NAME could not be stopped" ;;
-+        esac
-+        ;;
-   restart|force-reload)
+-  restart|force-reload)
 -	log_daemon_msg "Restarting $DESC" "$NAME"
 -	do_stop
 -	case "$?" in
@@ -172,30 +138,47 @@ Index: ipwatchd-1.2.1/src/scripts/ipwatchd
 -		;;
 -	esac
 -	;;
+-  *)
+-	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
+-	exit 3
+-	;;
++start)
++        do_start
++        case "$?" in
++        0) [ "$VERBOSE" != no ] && echo "Started $NAME, $DESC" ;;
++        1) [ "$VERBOSE" != no ] && echo "$NAME already running" ;;
++        2) [ "$VERBOSE" != no ] && echo "Start of $NAME failed" ;;
++        esac
++        ;;
++stop)
 +        do_stop
 +        case "$?" in
-+          0|1)
-+               do_start
++        0) [ "$VERBOSE" != no ] && echo "Stopped $NAME" ;;
++        1) [ "$VERBOSE" != no ] && echo "$NAME already stopped" ;;
++        2) [ "$VERBOSE" != no ] && echo "$NAME could not be stopped" ;;
++        esac
++        ;;
++restart | force-reload)
++        do_stop
++        case "$?" in
++        0 | 1)
++                do_start
 +                case "$?" in
-+                        0) echo "Restarted $NAME, $DESC" ;;
-+                        1) echo "Old process i$NAME is still running" ;;
-+                        *) echo "$NAME failed to start" ;;
++                0) echo "Restarted $NAME, $DESC" ;;
++                1) echo "Old process $NAME is still running" ;;
++                *) echo "$NAME failed to start" ;;
 +                esac
 +                ;;
-+          *)
++        *)
 +                # Failed to stop
 +                echo "$NAME failed to stop"
 +                ;;
 +        esac
 +        ;;
-   *)
--	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
--	exit 3
--	;;
++*)
 +        echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload}" >&2
 +        exit 3
 +        ;;
  esac
- 
+-
 -:
-+
diff --git a/projectroot/etc/config-tools/config_ethernet b/projectroot/etc/config-tools/config_ethernet
--- a/projectroot/etc/config-tools/config_ethernet
+++ b/projectroot/etc/config-tools/config_ethernet
@@ -14,14 +14,18 @@
 #-----------------------------------------------------------------------------#
 
 # load general definitions and functions
-if [[ ! -f "/etc/config-tools/config_tool_defines" ]]; then
-  echo "config_tool_defines missing"
+if [[ ! -f "/etc/config-tools/config_tool_lib" ]]; then
+  echo "config_tool_lib missing"
   exit 64
 fi
 
-. /etc/config-tools/config_tool_defines
+. /etc/config-tools/config_tool_lib
 
 status=$SUCCESS
+
+if [[ $# -lt 1 ]]; then
+    exit 1
+fi
 
 # show help-text if requested
 if [[ "$1" = "-h" ]] || [[ "$1" = "--help" ]]; then
@@ -29,11 +33,11 @@ if [[ "$1" = "-h" ]] || [[ "$1" = "--help" ]]; then
   echo "* Change the ethernet port settings *"
   echo
   echo "Usage: $0 < [interface=interface-value] port=port-value [state=state-value ] [ autoneg=autoneg-value ] [ speed=speed-value ] [duplex=duplex-value ]"
-  echo "With autoneg=on, no speed or duplex values have to be provided."
+  echo "With autoneg=enabled, no speed or duplex values have to be provided."
   echo
 # pfc200-specific settings
   echo "interface-value: eth0 [ignored]"
-  echo "port-value: $(/etc/config-tools/get_eth_config --print-ports)"
+  echo "port-value: $(GetPorts)"
   echo "state-value: enabled/disabled"
   echo "autoneg-value: enabled/disabled"
   echo "speed-value: 10M/100M"
@@ -44,6 +48,18 @@ fi
 
 declare -A params
 
+function is_supported_port {
+    value=$1
+
+    for port in $(GetPorts); do
+        if [[ "$value" == "$port" ]]; then
+            return 0
+        fi
+    done
+
+    return 1
+}
+
 while [[ $# -ne 0 ]]; do
     case "$1" in
         interface=*)
@@ -51,6 +67,9 @@ while [[ $# -ne 0 ]]; do
         port=*)
             port=${1#port=}
             params[device]="\"$port\""
+            if ! is_supported_port $port; then
+                status=${CONFIG_DATA_ERROR}
+            fi
             ;;
         state=*)
             value=${1#state=}
@@ -102,7 +121,7 @@ if [[ $status == $SUCCESS ]]; then
             json_content="$json_content,\"$i\":${params[$i]}"
         fi
     done
-    $($NETWORK_CONFIG --interface-config --set "{${json_content}}" --format=json)
+    $NETWORK_CONFIG --interface-config --set "{${json_content}}" --format=json --quiet
     status=$?
 fi
 
diff --git a/projectroot/etc/config-tools/events/networking/update_routing b/projectroot/etc/config-tools/events/networking/update_routing
--- a/projectroot/etc/config-tools/events/networking/update_routing
+++ b/projectroot/etc/config-tools/events/networking/update_routing
@@ -120,7 +120,7 @@ function DeleteDhcpDefaultGateways()
         if [[ "true" == "$_remove" ]]; then
             #Load dhcp-data-file content to array. Remove only gateways which are not part of this list.
             new_gateways=()
-    [[ -e  $DHCP_DATA_FILE_TEMPLATE$device_name ]] && new_gateways=($($AWK 'BEGIN{RS="[ \t\n]+"; FS="="} /DEFAULT_GATEWAY/ {print $2}' "$DHCP_DATA_FILE_TEMPLATE$device_name" ))
+            [[ -e  $DHCP_DATA_FILE_TEMPLATE$device_name ]] && new_gateways=($($AWK 'BEGIN{RS="[ \t\n]+"; FS="="} /DEFAULT_GATEWAY/ {print $2}' "$DHCP_DATA_FILE_TEMPLATE$device_name" ))
 
             # Load backup file content.
             . "$cfgfile"
@@ -172,7 +172,7 @@ function DeleteRoutes
             if [[ $is_valid == TRUE ]]; then
                 local index=0
                 # Remove static routes.
-                while [[ $index < $count ]]; do
+                while [[ $index -lt $count ]]; do
                     DeleteRoute "${static_dest_remove[$index]}" "${static_gw_remove[$index]}" "${static_dest_mask_remove[$index]}" "${static_metric_remove[$index]}"
                     ((index++))
                 done
@@ -241,11 +241,22 @@ function SetGeneralForwarding
 
 function SetMulticastRoutes
 {
+    local ret=$SUCCESS
+    local status=$SUCCESS
+
     local bridges=$($BRCTL show | $GREP -E '^[[:alpha:]]' | $AWK '(NR>1)  {print $1}')
     for bridge in $bridges; do
-        $ROUTE add -net 224.0.0.0 netmask 224.0.0.0 dev $bridge
-    Log "Set 224.0.0.0 on $bridge: result($?)"
+        ret=$($ROUTE add -net 224.0.0.0 netmask 224.0.0.0 dev $bridge 2>&1)
+        # Ignore duplicates
+        if [[ $? != 0 && $ret != "route: SIOCADDRT: File exists" ]]; then
+            status=$INVALID_PARAMETER
+            Log "Failed to add multicast route for bridge: $bridge"
+        else
+            Log "Set 224.0.0.0 on $bridge"
+        fi
     done
+
+    echo "$status"
 }
 
 function SetRoutes
@@ -260,7 +271,7 @@ function SetRoutes
     local count=0
     [[ "${static_dest[@]-}" ]] && count=${#static_dest[@]}
     # Configure static routes.
-    while [[ $index < $count ]]; do
+    while [[ $index -lt $count ]]; do
         if [[ "${static_state[$index]}" == "enabled" ]]; then
             if [[ "${static_dest[$index]}" && ( "${static_dest[$index]}" == "default" || "${static_dest[$index]}" == "0.0.0.0" ) ]]; then
                 # Default gateway
@@ -386,16 +397,18 @@ function DoUpdate
     ret=$(SetPortForwarding)
     [[ $ret != $SUCCESS ]] && status=$INTERNAL_ERROR
 
-		# Set multicast routes on all active bridges
-		SetMulticastRoutes
-		
+    # Set multicast routes on all active bridges
+    ret=$(SetMulticastRoutes)
+    [[ $ret != $SUCCESS ]] && status=$INTERNAL_ERROR
+
     sync
 
     # Apply previously set changes if no errors occurred.
     if [[ $status == "$SUCCESS" ]]; then 
         $FIREWALL iptables --apply &> /dev/null
     else
-        SetLastError "One or more errors occur during routing setup. See /var/log/messages for details."    
+        # Do not log last error when called by netconfd.
+        [[ -z ${NETCONF_IP_CONFIG+x} ]] && SetLastError "One or more errors occur during routing setup. See /var/log/messages for details."    
     fi
 
     echo "$status"
diff --git a/projectroot/etc/init.d/ipsec b/projectroot/etc/init.d/ipsec
--- a/projectroot/etc/init.d/ipsec
+++ b/projectroot/etc/init.d/ipsec
@@ -4,7 +4,7 @@
 # License, v. 2.0. If a copy of the MPL was not distributed with this
 # file, You can obtain one at http://mozilla.org/MPL/2.0/.
 #
-# Copyright (c) 2018 WAGO Kontakttechnik GmbH & Co. KG
+# Copyright (c) 2018-2020 WAGO Kontakttechnik GmbH & Co. KG
 
 ### BEGIN INIT INFO
 # Provides:          ipsec
@@ -51,31 +51,22 @@ FW_INITD=/etc/init.d/firewall
 #
 do_start()
 {
-	# Return
-	#   0 if daemon has been started
-	#   1 if daemon was already running
-	#   2 if daemon could not be started
+  # Return
+  #   0 if daemon has been started
+  #   1 if daemon was already running
+  #   2 if daemon could not be started
 
-	# test if charon is currently running
-	if [ -e $CHARON ]; then
-	  start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $STARTER --test > /dev/null \
-		|| return 1
-	fi
+  # test if charon is currently running
+  if [ -e $CHARON ]; then
+    start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $STARTER --test > /dev/null \
+    || return 1
+  fi
 
   local ret=0
-	$STARTER start || ret=2
-	if [[ $ret == 0 ]]; then
-      if [ -s $FW_DIR/ipsecfirewall.sh ]; then
-        sh $FW_DIR/ipsecfirewall.sh
-        if [[ "$?" == 3 ]]; then
-          sh $FW_INITD restart
-        fi  
-      else
-        log_daemon_msg "$FW_DIR/ipsecfirewall.sh is missing - can't execute."
-      fi
-  else 
-     return $ret
- fi      	
+  $STARTER start || ret=2
+  if [[ $ret != 0 ]]; then
+    return $ret
+   fi
 }
 
 #
@@ -83,93 +74,91 @@ do_start()
 #
 do_stop()
 {
-	# Return
-	#   0 if daemon has been stopped
-	#   1 if daemon was already stopped
-	#   2 if daemon could not be stopped
-	#   other if a failure occurred
-	# give the proper signal to stop
-	$STARTER stop || return 2
+  # Return
+  #   0 if daemon has been stopped
+  #   1 if daemon was already stopped
+  #   2 if daemon could not be stopped
+  #   other if a failure occurred
+  # give the proper signal to stop
+  $STARTER stop || return 2
 
-	RETVAL=0
-	# but kill if that didn't work
-	if [ -e $PIDFILE ]; then
-		start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
-		RETVAL="$?"
-		[ "$RETVAL" = 2 ] && return 2
-	fi
+  RETVAL=0
+  # but kill if that didn't work
+  if [ -e $PIDFILE ]; then
+    start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
+    RETVAL="$?"
+    [ "$RETVAL" = 2 ] && return 2
+  fi
 
-	# Wait for children to finish too if this is a daemon that forks
-	# and if the daemon is only ever run from this initscript.
-	# If the above conditions are not satisfied then add some other code
-	# that waits for the process to drop all resources that could be
-	# needed by services started subsequently.  A last resort is to
-	# sleep for some time.
-	if [ -e $CHARON ]; then
-	  start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $CHARON
-	  [ "$?" = 2 ] && return 2
-	fi
+  # Wait for children to finish too if this is a daemon that forks
+  # and if the daemon is only ever run from this initscript.
+  # If the above conditions are not satisfied then add some other code
+  # that waits for the process to drop all resources that could be
+  # needed by services started subsequently.  A last resort is to
+  # sleep for some time.
+  if [ -e $CHARON ]; then
+    start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $CHARON
+    [ "$?" = 2 ] && return 2
+  fi
 
-	# strongswan is known to leave PID files behind when something goes wrong, cleanup here
-	rm -f $PIDFILE
-	# and just to make sure they are really really dead at this point...
-	killall -9 $CHARON 2>/dev/null
+  # strongswan is known to leave PID files behind when something goes wrong, cleanup here
+  rm -f $PIDFILE
+  # and just to make sure they are really really dead at this point...
+  killall -9 $CHARON 2>/dev/null
 
-	return "$RETVAL"
+  return "$RETVAL"
 }
 
 do_reload() {
-	$STARTER reload
-	return 0
+  $STARTER reload
+  return 0
 }
 
 case "$1" in
   start)
-	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
-	do_start
-	case "$?" in
-		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
-	esac
-	;;
+    [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
+    do_start
+    case "$?" in
+      0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+      2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+    esac
+    ;;
   stop)
-	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
-	do_stop
-	case "$?" in
-		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
-	esac
-	;;
+    [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
+    do_stop
+    case "$?" in
+      0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+      2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+    esac
+    ;;
   status)
-	$STARTER status || exit $?
-	;;
+    $STARTER status || exit $?
+    ;;
   reload|force-reload)
-	log_daemon_msg "Reloading $DESC" "$NAME"
-	do_reload
-	log_end_msg $?
-	;;
+    log_daemon_msg "Reloading $DESC" "$NAME"
+    do_reload
+    log_end_msg $?
+    ;;
   restart)
-	log_daemon_msg "Restarting $DESC" "$NAME"
-	do_stop
-	case "$?" in
-	  0|1)
-		do_start
-		case "$?" in
-			0) log_end_msg 0 ;;
-			1) log_end_msg 1 ;; # Old process is still running
-			*) log_end_msg 1 ;; # Failed to start
-		esac
-		;;
-	  *)
-	  	# Failed to stop
-		log_end_msg 1
-		;;
-	esac
-	;;
+    log_daemon_msg "Restarting $DESC" "$NAME"
+    do_stop
+    case "$?" in
+      0|1)
+        do_start
+        case "$?" in
+          0) log_end_msg 0 ;;
+          1) log_end_msg 1 ;; # Old process is still running
+          *) log_end_msg 1 ;; # Failed to start
+        esac
+        ;;
+      *)
+        # Failed to stop
+        log_end_msg 1
+        ;;
+    esac
+    ;;
   *)
-	echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
-	exit 3
-	;;
+    echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
+    exit 3
+    ;;
 esac
-
-:
