Update 03.04.10-FW16  o Adding gitignore  o Using gitignore to remove already commited files

diff --git a/configs/wago-pfcXXX/projectroot/etc/init.d/finalize_root b/configs/wago-pfcXXX/projectroot/etc/init.d/finalize_root
--- a/configs/wago-pfcXXX/projectroot/etc/init.d/finalize_root
+++ b/configs/wago-pfcXXX/projectroot/etc/init.d/finalize_root
@@ -27,14 +27,19 @@ if [[ ! -x "$GET_FS_DATA" ]]; then
 fi
 
 if ! [[ "$($GET_FS_DATA active-partition-medium)" =~ internal-flash-.* ]]; then
-  echo "$0: DEBUG: root partition is not flash - do nothing."
+  #echo "$0: DEBUG: root partition is not flash - do nothing."
   exit 0
 fi
 
 case $1 in
 
   start)
-    [ -x ${RAUC} ] && ${RAUC} status mark-good && ${RAUC} status mark-active
+    [ -x ${RAUC} ] &&
+      ${RAUC} status mark-good > /dev/null &&
+      ${RAUC} status mark-active > /dev/null
+    if [[ $? -ne 0 ]]; then
+      echo "Error: Failed to mark the active system as good!"
+    fi
   ;;
   stop)
   ;;
diff --git a/local_src/netconfd/root/etc/init.d/netconfd b/local_src/netconfd/root/etc/init.d/netconfd
--- a/local_src/netconfd/root/etc/init.d/netconfd
+++ b/local_src/netconfd/root/etc/init.d/netconfd
@@ -8,38 +8,42 @@
 
 RUNDIR="/var/run/netconfd"
 PIDFILE="netconfd.pid"
-STARTCMD="/usr/bin/netconfd --daemon --rundir=$RUNDIR --pidfile=$PIDFILE --loglevel=info"
+PATHPIDFILE=$RUNDIR/$PIDFILE
+NETCONFD="/usr/bin/netconfd"
+STARTCMD="$NETCONFD --daemon --rundir=$RUNDIR --pidfile=$PIDFILE"
 
 set -e
 
-function wait_for_dbus () {
-	dbus-wait -t 30 de.wago.netconfd
-	if [ $? != 0 ]; then
-	  logger -t netconfd.init.d "ERROR: netconfd: DBUS interface de.wago.netconfd not reachable!"
-	  exit -1
-	fi
+function stop_netconfd {
+    start-stop-daemon --stop --pidfile $PATHPIDFILE --retry=TERM/20/KILL/10 --oknodo --exec $NETCONFD
+    /usr/bin/rm -f $PATHPIDFILE
+}
+
+function wait_for_netconfd_ready {
+   dbus-wait -t 30 de.wago.netconfd
+   if [ $? != 0 ]; then
+     logger -t netconfd.init.d "ERROR: netconfd: DBUS interface de.wago.netconfd not reachable!"
+     exit -1
+   fi
 }
 
 case $1 in
 start)
     $STARTCMD
-    wait_for_dbus
+    wait_for_netconfd_ready
     echo "done"
     ;;
 
 stop)
     echo "Stopping network configuration daemon"
-    if [ -f "$RUNDIR/$PIDFILE" ]; then
-        kill $(<$RUNDIR/$PIDFILE)
-        rm -f $RUNDIR/$PIDFILE
-    fi
+    stop_netconfd
     ;;
 
 restart)
     echo "Restart network configuration daemon"
-    [ -f "$RUNDIR/$PIDFILE" ] && kill $(<$RUNDIR/$PIDFILE)
+    stop_netconfd
     $STARTCMD
-    wait_for_dbus
+    wait_for_netconfd_ready
     echo "done"
     ;;
 
diff --git a/projectroot/etc/config-tools/pbdp_config b/projectroot/etc/config-tools/pbdp_config
--- a/projectroot/etc/config-tools/pbdp_config
+++ b/projectroot/etc/config-tools/pbdp_config
@@ -1,16 +1,21 @@
 #!/bin/bash
+#-----------------------------------------------------------------------------#
 # This Source Code Form is subject to the terms of the Mozilla Public
 # License, v. 2.0. If a copy of the MPL was not distributed with this
 # file, You can obtain one at http://mozilla.org/MPL/2.0/.
 #
-# Copyright (c) 2018 WAGO Kontakttechnik GmbH & Co. KG
-
+# This file is part of PTXdist package config-tools.
+#
+# Copyright (c) 2012-2020 WAGO Kontakttechnik GmbH & Co. KG
 #-----------------------------------------------------------------------------#
-# Script-name: pbdb_config
+#-----------------------------------------------------------------------------#
+# Script:   pbdb_config
 #
-# Get config value of pbdpslvappl.conf file
+# Brief:    Get config value of dps.conf file.
 #
-# Author: WAGO Kontakttechnik GmbH
+# Author:   SM:  WAGO Kontakttechnik GmbH & Co. KG
+# Author:   AGa: WAGO Kontakttechnik GmbH & Co. KG
+# Author:   PEn: WAGO Kontakttechnik GmbH & Co. KG
 #-----------------------------------------------------------------------------#
 
 # load general definitions and functions
@@ -23,117 +28,204 @@ fi
 
 PBDP_CONFIG_FILE="/etc/specific/dps.conf"
 
-# show help-text if requested
-if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
-  echo
+
+# Main tool/script function.
+#
+# Param 1..n: Script parameters
+#
+# Return: Exit code, 0 on success, unequal to 0 otherwise
+#-----------------------------------------------------------------------------#
+main()
+{
+  local status=$SUCCESS
+
+  # show help-text if requested
+  if [ "$1" = "-h" ] || [ "$1" = "--help" ] || [ "$1" = "help" ]; then
+    print_help
+    exit $?
+  fi
+  
+  if [ "$1" = "reset-ssa" ]; then
+    reset_ssa
+    status=$?
+  else
+    read_write_config "$@"
+    status=$?
+  fi
+
+  return $status
+}
+
+
+# Function to print tool/script help text.
+#
+# Return: 0 on success, unequal to 0 otherwise
+#-----------------------------------------------------------------------------#
+print_help()
+{
   echo "* Get and set configuration values of dps.conf file *"
   echo
-  echo "Usage: pbdb_config < access parameter-area parameter-name > [ new-parameter-value ]"
-  echo 
-  echo "access: \"get\" | \"set\""
-  echo 
-  exit $SUCCESS
-fi
+  echo "Usage:"
+  echo "  pbdb_config [<script options>] <command> [<parameter-area> <parameter-name> [<new-parameter-value>]]"
+  echo
+  echo "Script commands:"
+  echo "  help                  See script option \"--help\""
+  echo "  get                   Get parameter <parameter-name> from <parameter-area>"
+  echo "  set                   Set parameter <parameter-name> in <parameter-area> to <new-parameter-value>"
+  echo "  reset-ssa             Reset SSA values"
+  echo
+  echo "Script options:"
+  echo "  --help           -h   Prints this help text"
 
-status=$SUCCESS
+  return 0
+}
 
-# read input parameter
-access=$1
-area=$2
-paramName=$3
-newParamValue=$4
-#echo "access:${access} area:${area} paramName:${paramName} newParamValue:${newParamValue}" > /etc/config-tools/output
 
-# check for missing input parameter
-if [ -z "$access" ] || [ -z "$area" ] || [ -z "$paramName" ]; then
-  status=$MISSING_PARAMETER
-  SetLastError "Missing input parameter"
-  exit $status
-fi
+# Function to read or write configuration value.
+#
+# Param 1: Access specifier (get|set)
+# Param 2: Parameter area to access
+# Param 3: Parameter name to access
+# Param 4: New parameter value to set (only for set access specifier)
+#
+# Return: 0 on success, specific error value otherwise
+#-----------------------------------------------------------------------------#
+read_write_config()
+{
+  local status=$SUCCESS
 
-#check whether config-file exists 
-if [ ! -f $PBDP_CONFIG_FILE ]; then
-  status=$CONFIG_FILE_MISSING
-  SetLastError "Config File is missing"
-  exit $status
-fi
+  # read input parameter
+  local access=${1:-}
+  local area=${2:-}
+  local paramName=${3:-}
+  local newParamValue=${4:-}
+  #echo "access:${access} area:${area} paramName:${paramName} newParamValue:${newParamValue}" > /etc/config-tools/output
 
-# get line count of file for "end of file" check
-maxLineCount=`cat $PBDP_CONFIG_FILE | wc -l`
-#echo "maxLineCount:"$maxLineCount
+  # check for missing input parameter
+  if [ -z "$access" ] || [ -z "$area" ] || [ -z "$paramName" ]; then
+    status=$MISSING_PARAMETER
+    SetLastError "Missing input parameter"
+    return $status
+  fi
 
-# init status with "can't find parameter"
-status=$CONFIG_DATA_ERROR
+  #check whether config-file exists 
+  if [ ! -f $PBDP_CONFIG_FILE ]; then
+    status=$CONFIG_FILE_MISSING
+    SetLastError "Config File is missing"
+    return $status
+  fi
 
-sectionEnd=0
-foundLine=0
-paramValue=""
+  # get line count of file for "end of file" check
+  maxLineCount=`cat $PBDP_CONFIG_FILE | wc -l`
+  #echo "maxLineCount:"$maxLineCount > /etc/config-tools/output
 
-# get the line number of the line with start of area (cut the number from grep output line)
-numberedLine=`grep -n "^ *\[${area}\] *$" $PBDP_CONFIG_FILE`
-#echo "$numberedLine"
+  # init status with "can't find parameter"
+  status=$CONFIG_DATA_ERROR
 
-# if we can't find area at all, there is no need to search for parameter - don't start following loop
-if [ -z $numberedLine ]; then
-  sectionEnd=1
-else
-  lineNo=`echo ${numberedLine%:*}`
-fi
+  sectionEnd=0
+  foundLine=0
+  paramValue=""
 
-# loop over the following lines until we find the requestet param or start of next area or end of file
+  # get the line number of the line with start of area (cut the number from grep output line)
+  numberedLine=`grep -n "^ *\[${area}\] *$" $PBDP_CONFIG_FILE`
+  #echo "$numberedLine" > /etc/config-tools/output
 
-while [ "$sectionEnd" = 0 ] && [ "$foundLine" = 0 ]; do
-
-  lineNo=$[$lineNo + 1]
-  
-  # end of file? -> break loop without success 
-  if (( $lineNo > $maxLineCount )); then
-    #echo end of file
+  # if we can't find area at all, there is no need to search for parameter - don't start following loop
+  if [ -z $numberedLine ]; then
     sectionEnd=1
   else
-  
-    # read actual line
-    line=`sed -n ''${lineNo}'p' $PBDP_CONFIG_FILE`
-    #echo $line
+    lineNo=`echo ${numberedLine%:*}`
+  fi
 
-    # check if line already contains start of next area (-> would mean, param was not existing in requested area)
-    echo $line | grep "^ *\[" > /dev/null 2> /dev/null
-    if [ $? = $SUCCESS ]; then
+  # loop over the following lines until we find the requestet param or start of next area or end of file
+  while [ "$sectionEnd" = 0 ] && [ "$foundLine" = 0 ]; do
+
+    lineNo=$[$lineNo + 1]
+
+    # end of file? -> break loop without success 
+    if (( $lineNo > $maxLineCount )); then
+      #echo end of file > /etc/config-tools/output
       sectionEnd=1
-      #echo "section end"
-    
     else
-  
-      # check if this line contains our requested parameter
-      echo $line | grep "^ *${paramName}=" > /dev/null 2> /dev/null
-      if [ $? = $SUCCESS ]; then
-     
-        foundLine=1
-      
-        # user wants to get value - filter param value, write it to stdout and stop loop
-        if [ "get" = "$access" ]; then
-          status=$SUCCESS
-          paramValue=`echo ${line#${paramName}=}`
-          printf "%s" $paramValue
-      
-        # user wants to set value - write new parameter to line 
-        elif [ "set" = "$access" ]; then
-          status=$SUCCESS
-          sed -i ''$lineNo'c '$paramName'='$newParamValue'' $PBDP_CONFIG_FILE > /dev/null 2> /dev/null
-          if [[ "$?" == "$SUCCESS" ]]; then
-            sync
-          else
-            status=$WRITE_FILE_ERROR
-          fi
 
-        # unknown access
-        else
-          status=$INVALID_PARAMETER
+      # read actual line
+      line=`sed -n ''${lineNo}'p' $PBDP_CONFIG_FILE`
+      #echo $line > /etc/config-tools/output
+
+      # check if line already contains start of next area (-> would mean, param was not existing in requested area)
+      echo $line | grep "^ *\[" > /dev/null 2> /dev/null
+      if [ $? = $SUCCESS ]; then
+        sectionEnd=1
+        #echo "section end" > /etc/config-tools/output
+
+      else
+
+        # check if this line contains our requested parameter
+        echo $line | grep "^ *${paramName}=" > /dev/null 2> /dev/null
+        if [ $? = $SUCCESS ]; then
+
+          foundLine=1
+
+          # user wants to get value - filter param value, write it to stdout and stop loop
+          if [ "get" = "$access" ]; then
+            status=$SUCCESS
+            paramValue=`echo ${line#${paramName}=}`
+            printf "%s" $paramValue
+
+          # user wants to set value - write new parameter to line 
+          elif [ "set" = "$access" ]; then
+            status=$SUCCESS
+            sed -i ''$lineNo'c '$paramName'='$newParamValue'' $PBDP_CONFIG_FILE > /dev/null 2> /dev/null
+            if [[ "$?" == "$SUCCESS" ]]; then
+              sync
+            else
+              status=$WRITE_FILE_ERROR
+            fi
+
+          # unknown access
+          else
+            status=$INVALID_PARAMETER
+          fi
         fi
       fi
     fi
-  fi
-  
-done
 
-exit $status
+  done
+
+  return $status
+}
+
+
+# Function to reset SSA values to factory default.
+#
+# Return: 0 on success, specific error value otherwise
+#-----------------------------------------------------------------------------#
+reset_ssa()
+{
+  local status=$SUCCESS
+
+  local ssa_release=""
+  local slave_address=""
+
+  ssa_release="$(read_write_config "get" "ssa.factory" "ssa_released")"
+  status=$(( $? == 0 ? $status : $? ))
+  slave_address="$(read_write_config "get" "ssa.factory" "slave_address")"
+  status=$(( $? == 0 ? $status : $? ))
+
+  if [ $status -eq 0 ]; then
+    read_write_config "set" "ssa.user" "ssa_released" "$ssa_release"
+    status=$?
+  fi
+
+  if [ $status -eq 0 ]; then
+    read_write_config "set" "ssa.user" "slave_address" "$slave_address"
+    status=$?
+  fi
+
+  return $status
+}
+
+
+# Start main function
+main "$@"
+exit $?
diff --git a/projectroot/etc/init.d/generate_password b/projectroot/etc/init.d/generate_password
--- a/projectroot/etc/init.d/generate_password
+++ b/projectroot/etc/init.d/generate_password
@@ -6,29 +6,30 @@
 #
 # Copyright (c) 2018 WAGO Kontakttechnik GmbH & Co. KG
 
-DONE="==> done."
-FAILED="==> failed!"
-PASSFILE="/tmp/password_webserver"
+DONE=' ==> done.'
+FAILED=' ==> failed!'
+PASSFILE_DIR='/var/run/webserver'
+PASSFILE="${PASSFILE_DIR}/password_webserver"
 
-echo "Generate new password..."
-NEWPASS=$(dd if=/dev/urandom count=40c 2>/dev/null | md5sum | cut -d ' ' -f 1)
-echo $DONE
-echo "Update password of "visualisation" user..."
-/etc/config-tools/config_linux_user user=visualisation new-password=$NEWPASS confirm-password=$NEWPASS
-if [ $(echo $?) == "0" ]
-  then
-    echo $DONE
-  else
-    echo $FAILED
-    exit
+mkdir -p "${PASSFILE_DIR}" || exit 1
+
+echo -n 'Generate new password...'
+new_passwd="$(</dev/urandom tr -dc 'A-Za-z0-9!"'\''#%&()*+,-./:;<=>?@[]^_`{|}~' | dd bs=1 count=32 status=none)"
+echo "${DONE}"
+
+echo -n 'Update password of "visualisation" user...'
+if echo -e "${new_passwd}\n${new_passwd}\n" | passwd 'visualisation' 1>/dev/null 2>&1; then
+  echo "${DONE}"
+else
+  echo "${FAILED}"
+  exit 1
 fi
 
-echo "Create temporary password file for the webserver (overwrite if exists)..."
-rm -f $PASSFILE
-#Note! Only 'root' shall access the generated password file.
-UMASK_SAVED=$(umask)
-umask o-rwx
-echo $NEWPASS > $PASSFILE
-umask $UMASK_SAVED
-echo $DONE
+echo -n 'Create temporary password file for the webserver (overwrite if exists)...'
+# Note: Only 'root' shall has access to the generated password file!
+old_umask="$(umask)"
+umask 177
+echo "${new_passwd}" > "${PASSFILE}.tmp" && mv "${PASSFILE}.tmp" "${PASSFILE}"
+umask "${old_umask}"
+echo "$DONE"
 
